name: Build Server
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:

      - uses: docker/login-action@v2.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v4.0.1
        id: meta
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
          labels: |
            maintainer=João Miguel Marques Silva <joao@miguel.ms>

      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug

      - uses: docker/build-push-action@v3.0.0
        with:
          file: .docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: HTTP Request Action
      #   if: ${{ github.ref == 'refs/heads/main' }}
      #   uses: fjogeleit/http-request-action@v1.10.0
      #   with:
      #     url: ${{ secrets.DOCKER_WEBHOOK_URL }}
      #     method: POST
      #     preventFailureOnNoResponse: "true"
